[workspace]
resolver = "3"
members = ["winnow-args", "winnow-args-derive", "bench", "bench/shadow-mise"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
winnow = { path = "../winnow", version = "1.0.4", default-features = false, features = ["std", "parser"] }
winnow-args = { path = "winnow-args", version = "0.1.0", default-features = false, features = ["derive"] }
winnow-args-derive = { path = "winnow-args-derive", version = "=0.1.0" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[profile.release]
debug = 1
