[package]
name = "winnow-args-man"
description = "man pages for a stitched winnow-args command"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["cli", "argument", "parser", "winnow"]
categories = ["command-line-interface"]

[dependencies]
roff = "1.1"
winnow-args-spec.workspace = true
