//! brush's builtins, as its `winnow-port` branch declares them: each parses
//! its arguments and prints what it got. Generated by `tools/examples.py`.
//!
//! ```text
//! cargo run --example brush_builtins -- set -eu +x -o pipefail a b
//! cargo run --example brush_builtins -- declare -i +x n=1
//! cargo run --example brush_builtins -- read -rp 'name: ' -t 2.5 first last
//! cargo run --example brush_builtins -- echo -n --help
//! cargo run --example brush_builtins -- kill --help
//! ```
//!
//! With `PARSE_N=n` in the environment the line is parsed `n` times and
//! nothing is printed, to measure the parse alone.

use std::path::PathBuf;

use winnow_args::{Args, Subcommand};

/// Parse a brush builtin's arguments and print the result.
#[derive(Debug, Args)]
#[arg(
    name = "brush_builtins",
    after_help = "Each builtin has its own `--help` (not `echo` and `test`, which take every word). \
                  `set` and `declare` take `+x` options; `declare` stops at its first operand."
)]
struct Cli {
    #[arg(subcommand)]
    builtin: Builtin,
}

#[derive(Debug, Subcommand)]
enum Builtin {
    /// Manage aliases within the shell.
    #[arg(name = "alias")]
    Alias(AliasCommand),
    /// Change the current shell working directory.
    #[arg(name = "cd")]
    Cd(CdCommand),
    /// Display or update variables and their attributes.
    #[arg(name = "declare")]
    Declare(DeclareCommand),
    /// Echo text to standard output.
    #[arg(name = "echo")]
    Echo(EchoCommand),
    /// Parse command options.
    #[arg(name = "getopts")]
    GetOpts(GetOptsCommand),
    #[arg(name = "hash")]
    Hash(HashCommand),
    /// Query or manipulate the shell's command history.
    #[arg(name = "history")]
    History(HistoryCommand),
    /// Signal a job or process.
    #[arg(name = "kill")]
    Kill(KillCommand),
    /// Format a string.
    #[arg(name = "printf")]
    Printf(PrintfCommand),
    /// Display the current working directory.
    #[arg(name = "pwd")]
    Pwd(PwdCommand),
    /// Parse standard input.
    #[arg(name = "read")]
    Read(ReadCommand),
    /// Manage set-based shell options.
    #[arg(name = "set")]
    Set(SetCommand),
    /// Manage shopt-style options.
    #[arg(name = "shopt")]
    Shopt(ShoptCommand),
    /// Evaluate test expression.
    #[arg(name = "test")]
    Test(TestCommand),
    /// Inspect the type of a named shell item.
    #[arg(name = "type")]
    Type(TypeCommand),
    /// Manage the process umask.
    #[arg(name = "umask")]
    Umask(UmaskCommand),
    /// Unset a variable.
    #[arg(name = "unset")]
    Unset(UnsetCommand),
}

/// Manage aliases within the shell.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct AliasCommand {
    /// Print all defined aliases in a reusable format.
    #[arg(short = 'p')]
    print: bool,

    /// List of aliases to display or update.
    #[arg(positional)]
    aliases: Vec<String>,
}

/// Change the current shell working directory.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct CdCommand {
    /// Force following symlinks.
    #[arg(short = 'L', overrides = "-P")]
    force_follow_symlinks: bool,

    /// Use physical dir structure without following symlinks.
    #[arg(short = 'P', overrides = "-L")]
    use_physical_dir: bool,

    /// Exit with non zero exit status if current working directory resolution fails.
    #[arg(short = 'e')]
    exit_on_failed_cwd_resolution: bool,

    /// Show file with extended attributes as a dir with extended
    /// attributes.
    #[arg(short = '@')]
    file_with_xattr_as_dir: bool,

    /// By default it is the value of the HOME shell variable. If `TARGET_DIR` is "-", it is
    /// converted to $OLDPWD.
    #[arg(positional)]
    target_dir: Option<PathBuf>,
}

/// Display or update variables and their attributes.
#[derive(Debug, Args)]
#[arg(
    plus_options,
    disable_help_short,
    disable_version_flag,
    disable_help_subcommand
)]
struct DeclareCommand {
    /// Constrain to function names or definitions.
    #[arg(short = 'f')]
    function_names_or_defs_only: bool,

    /// Constrain to function names only.
    #[arg(short = 'F')]
    function_names_only: bool,

    /// Create global variable, if applicable.
    #[arg(short = 'g')]
    create_global: bool,

    /// When creating a local variable that shadows another variable of the same name,
    /// then initialize it with the contents and attributes of the variable being shadowed.
    #[arg(short = 'I')]
    locals_inherit_from_prev_scope: bool,

    /// Display each item's attributes and values.
    #[arg(short = 'p')]
    print: bool,

    #[arg(short = 'a', plus = 'a')]
    make_indexed_array: Option<bool>,

    #[arg(short = 'A', plus = 'A')]
    make_associative_array: Option<bool>,

    #[arg(short = 'c', plus = 'c')]
    capitalize_value_on_assignment: Option<bool>,

    #[arg(short = 'l', plus = 'l')]
    lowercase_value_on_assignment: Option<bool>,

    #[arg(short = 'x', plus = 'x')]
    make_exported: Option<bool>,

    #[arg(short = 'i', plus = 'i')]
    make_integer: Option<bool>,

    #[arg(short = 'n', plus = 'n')]
    make_nameref: Option<bool>,

    #[arg(short = 'r', plus = 'r')]
    make_readonly: Option<bool>,

    #[arg(short = 't', plus = 't')]
    make_traced: Option<bool>,

    #[arg(short = 'u', plus = 'u')]
    uppercase_value_on_assignment: Option<bool>,

    /// Names and assignments.
    #[arg(positional, stop_flags)]
    declarations: Vec<String>,
}

/// Echo text to standard output.
#[derive(Debug, Args)]
#[arg(
    disable_help_flag,
    disable_version_flag,
    disable_help_subcommand,
    unknown_flags = "value"
)]
struct EchoCommand {
    /// Suppress the trailing newline from the output.
    #[arg(short = 'n')]
    no_trailing_newline: bool,

    /// Interpret backslash escapes in the provided text.
    #[arg(short = 'e', overrides = "-E")]
    interpret_backslash_escapes: bool,

    /// Do not interpret backslash escapes in the provided text.
    #[arg(short = 'E', overrides = "-e")]
    no_interpret_backslash_escapes: bool,

    /// Tokens to echo to standard output.
    #[arg(positional, double_dash = "preserve", stop_flags)]
    args: Vec<String>,
}

/// Parse command options.
#[derive(Debug, Args)]
#[arg(
    unknown_flags = "value",
    disable_help_flag,
    disable_version_flag,
    disable_help_subcommand
)]
struct GetOptsCommand {
    /// Specification for options
    #[arg(positional)]
    options_string: String,
    /// Name of variable to receive next option
    #[arg(positional)]
    variable_name: String,
    /// Arguments to parse
    #[arg(positional, double_dash = "preserve")]
    args: Vec<String>,
}

#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct HashCommand {
    /// Display paths in a format usable for input.
    #[arg(short = 'l')]
    display_as_usable_input: bool,

    /// Remove all entries.
    #[arg(short = 'r')]
    remove_all: bool,

    /// The path to associate with the names.
    #[arg(short = 'p', value_name = "PATH")]
    path_to_use: Option<PathBuf>,

    /// Remove entries associated with the given names.
    #[arg(short = 'd')]
    remove: bool,

    /// Display the paths associated with the names.
    #[arg(short = 't')]
    display_paths: bool,

    /// Names to process.
    #[arg(positional)]
    names: Vec<String>,
}

/// Query or manipulate the shell's command history.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct HistoryCommand {
    /// Clears all history.
    #[arg(short = 'c')]
    clear_history: bool,

    /// Deletes the history entry at the given offset. Positive offsets are relative to the
    /// beginning of the history, while negative offsets are relative to the end of the history.
    #[arg(short = 'd', value_name = "OFFSET", allow_negative_numbers)]
    delete_offset: Option<i64>,

    /// Appends the history from the current session to the history file.
    #[arg(
        short = 'a',
        value_name = "HIST_FILE",
        value_optional,
        default_missing = "\u{0}"
    )]
    append_session_to_file: Option<String>,

    /// Appends any remaining history from the history file to the current session.
    #[arg(
        short = 'n',
        value_name = "HIST_FILE",
        value_optional,
        default_missing = "\u{0}"
    )]
    append_rest_of_file_to_session: Option<String>,

    /// Appends the history from the history file to the current session.
    #[arg(
        short = 'r',
        value_name = "HIST_FILE",
        value_optional,
        default_missing = "\u{0}"
    )]
    append_file_to_session: Option<String>,

    /// Replaces the history file with the current session history.
    #[arg(
        short = 'w',
        value_name = "HIST_FILE",
        value_optional,
        default_missing = "\u{0}"
    )]
    write_session_to_file: Option<String>,

    /// History-expands positional arguments and displays them.
    #[arg(short = 'p')]
    expand: bool,

    /// Appends positional arguments as an entry in the current session.
    #[arg(short = 's')]
    append: bool,

    /// Arguments.
    #[arg(positional, double_dash = "automatic", allow_negative_numbers)]
    args: Vec<String>,
}

/// Signal a job or process.
#[derive(Debug, Args)]
#[arg(
    disable_help_short,
    disable_version_flag,
    disable_help_subcommand,
    unknown_flags = "value"
)]
struct KillCommand {
    /// Name of the signal to send.
    #[arg(short = 's', value_name = "SIG_NAME")]
    signal_name: Option<String>,

    /// Number of the signal to send.
    #[arg(short = 'n', value_name = "SIG_NUM")]
    signal_number: Option<usize>,

    /// List known signal names.
    #[arg(short = 'l', short = 'L')]
    list_signals: bool,

    #[arg(positional, allow_negative_numbers)]
    args: Vec<String>,
}

/// Format a string.
#[derive(Debug, Args)]
#[arg(disable_help_flag, disable_version_flag, disable_help_subcommand)]
struct PrintfCommand {
    /// If specified, the output of the command is assigned to this variable.
    #[arg(short = 'v', allow_hyphen_values)]
    output_variable: Option<String>,

    /// Format string + arguments to the format string.
    ///
    /// N.B. We intentionally do *not* enable `allow_hyphen_values` here. Doing so would
    /// cause an attached short-option value such as `-va` (i.e. `-v a`) to be misparsed as
    /// a positional argument. With it disabled, a format string that genuinely needs to
    /// start with a hyphen must be preceded by `--`, matching other shells' behavior.
    #[arg(positional, double_dash = "automatic", required)]
    format_and_args: Vec<String>,
}

/// Display the current working directory.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct PwdCommand {
    /// Print $PWD if it names the current working directory.
    #[arg(short = 'L', overrides = "-P")]
    allow_symlinks: bool,

    /// Print the physical directory without any symlinks.
    #[arg(short = 'P', overrides = "-L")]
    physical: bool,
}

/// Parse standard input.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct ReadCommand {
    /// Use readline-like input.
    #[arg(short = 'e')]
    use_readline: bool,

    /// Read input in raw mode; no escape sequences.
    #[arg(short = 'r')]
    raw_mode: bool,

    /// Do not echo input.
    #[arg(short = 's')]
    silent: bool,

    /// Optionally, name of an array variable to receive read words
    /// of input.
    #[arg(short = 'a', value_name = "VAR_NAME")]
    array_variable: Option<String>,

    /// Optionally, a delimiter to use other than a newline character.
    #[arg(short = 'd')]
    delimiter: Option<String>,

    /// Provide text to use as initial input for readline.
    #[arg(short = 'i', value_name = "STR")]
    initial_text: Option<String>,

    /// Read only the first N characters or until a specified
    /// delimiter is reached, whichever happens first.
    #[arg(short = 'n', value_name = "COUNT")]
    return_after_n_chars: Option<usize>,

    /// Read exactly N characters, ignoring any specified delimiter.
    #[arg(short = 'N', value_name = "COUNT")]
    return_after_n_chars_no_delimiter: Option<usize>,

    /// Prompt to display before reading.
    #[arg(short = 'p')]
    prompt: Option<String>,

    /// Specify timeout in seconds; fail if the timeout elapses before
    /// input is completed.
    #[arg(short = 't', value_name = "SECONDS", allow_negative_numbers)]
    timeout_in_seconds: Option<f64>,

    /// File descriptor to read from instead of stdin.
    #[arg(short = 'u', value_name = "FD")]
    fd_num_to_read: Option<u8>,

    /// Optionally, names of variables to receive read input.
    #[arg(positional)]
    variable_names: Vec<String>,
}

/// Manage set-based shell options.
#[derive(Debug, Args)]
#[arg(
    plus_options,
    disable_help_short,
    disable_version_flag,
    disable_help_subcommand
)]
struct SetCommand {
    #[arg(short = 'a', plus = 'a')]
    export_variables_on_modification: Option<bool>,

    #[arg(short = 'b', plus = 'b')]
    notify_job_termination_immediately: Option<bool>,

    #[arg(short = 'e', plus = 'e')]
    exit_on_nonzero_command_exit: Option<bool>,

    #[arg(short = 'f', plus = 'f')]
    disable_filename_globbing: Option<bool>,

    #[arg(short = 'h', plus = 'h')]
    remember_command_locations: Option<bool>,

    #[arg(short = 'k', plus = 'k')]
    place_all_assignment_args_in_command_env: Option<bool>,

    #[arg(short = 'm', plus = 'm')]
    enable_job_control: Option<bool>,

    #[arg(short = 'n', plus = 'n')]
    do_not_execute_commands: Option<bool>,

    #[arg(short = 'p', plus = 'p')]
    real_effective_uid_mismatch: Option<bool>,

    #[arg(short = 't', plus = 't')]
    exit_after_one_command: Option<bool>,

    #[arg(short = 'u', plus = 'u')]
    treat_unset_variables_as_error: Option<bool>,

    #[arg(short = 'v', plus = 'v')]
    print_shell_input_lines: Option<bool>,

    #[arg(short = 'x', plus = 'x')]
    print_commands_and_arguments: Option<bool>,

    #[arg(short = 'B', plus = 'B')]
    perform_brace_expansion: Option<bool>,

    #[arg(short = 'C', plus = 'C')]
    disallow_overwriting_regular_files_via_output_redirection: Option<bool>,

    #[arg(short = 'E', plus = 'E')]
    shell_functions_inherit_err_trap: Option<bool>,

    #[arg(short = 'H', plus = 'H')]
    enable_bang_style_history_substitution: Option<bool>,

    #[arg(short = 'P', plus = 'P')]
    do_not_resolve_symlinks_when_changing_dir: Option<bool>,

    #[arg(short = 'T', plus = 'T')]
    shell_functions_inherit_debug_and_return_traps: Option<bool>,

    /// Set the named option (`-o NAME`); alone, list the options.
    #[arg(short = 'o', value_name = "OPT", default_missing = "\u{0}")]
    enable: Vec<String>,

    /// Unset the named option (`+o NAME`); alone, list them as commands.
    #[arg(plus = 'o', value_name = "OPT", default_missing = "\u{0}")]
    disable: Vec<String>,

    #[arg(positional, double_dash = "preserve", stop_flags)]
    positional_args: Vec<String>,
}

/// Manage shopt-style options.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct ShoptCommand {
    /// Manage set -o options.
    #[arg(short = 'o')]
    set_o_names_only: bool,

    /// Print options' current values.
    #[arg(short = 'p')]
    print: bool,

    /// Suppress typical output.
    #[arg(short = 'q')]
    quiet: bool,

    /// Set the specified options.
    #[arg(short = 's')]
    set: bool,

    /// Unset the specified options.
    #[arg(short = 'u')]
    unset: bool,

    /// Names of options to operate on.
    #[arg(positional)]
    options: Vec<String>,
}

/// Evaluate test expression.
#[derive(Debug, Args)]
#[arg(
    unknown_flags = "value",
    disable_help_flag,
    disable_version_flag,
    disable_help_subcommand
)]
struct TestCommand {
    #[arg(positional, double_dash = "preserve")]
    args: Vec<String>,
}

/// Inspect the type of a named shell item.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct TypeCommand {
    /// Display all locations of the specified name, not just the first.
    #[arg(short = 'a')]
    all_locations: bool,

    /// Don't consider functions when resolving the name.
    #[arg(short = 'f')]
    suppress_func_lookup: bool,

    /// Force searching by file path, even if the name is an alias, built-in
    /// command, or shell function.
    #[arg(short = 'P')]
    force_path_search: bool,

    /// Show file path only.
    #[arg(short = 'p')]
    show_path_only: bool,

    /// Only display the type of the specified name.
    #[arg(short = 't')]
    type_only: bool,

    /// Names to search for.
    #[arg(positional)]
    names: Vec<String>,
}

/// Manage the process umask.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct UmaskCommand {
    /// If MODE is omitted, output in a form that may be reused as input.
    #[arg(short = 'p')]
    print_roundtrippable: bool,

    /// Makes the output symbolic; otherwise an octal number is given.
    #[arg(short = 'S')]
    symbolic_output: bool,

    /// Mode mask.
    #[arg(positional)]
    mode: Option<String>,
}

/// Unset a variable.
#[derive(Debug, Args)]
#[arg(disable_help_short, disable_version_flag, disable_help_subcommand)]
struct UnsetCommand {
    #[arg(flatten)]
    name_interpretation: UnsetNameInterpretation,

    /// Names of variables to unset.
    #[arg(positional)]
    names: Vec<String>,
}

#[derive(Debug, Args)]
struct UnsetNameInterpretation {
    /// Treat each name as a shell function.
    #[arg(short = 'f')]
    shell_functions: bool,

    /// Treat each name as a shell variable.
    #[arg(short = 'v')]
    shell_variables: bool,

    /// Treat each name as a name reference.
    #[arg(short = 'n')]
    name_references: bool,
}

fn main() {
    let args: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();
    if let Some(n) = std::env::var("PARSE_N")
        .ok()
        .and_then(|n| n.parse::<usize>().ok())
    {
        let words = winnow_args::words(&args);
        for _ in 0..n {
            let _ = std::hint::black_box(Cli::parse_from(std::hint::black_box(&words)));
        }
        return;
    }
    match Cli::try_parse_from(&args) {
        Ok(cli) => println!("{:#?}", cli.builtin),
        Err(error) => std::process::exit(winnow_args::report(&error, "brush_builtins")),
    }
}
