//! usage's mise shadow, translated into winnow-args' vocabulary.
//!
//! Every `#[usage(...)]` item is mapped or dropped by name; an unknown one is
//! an error. Every struct is `unknown_flags = "value"`, usage's default. A
//! selector naming no field of its own struct (an ancestor's global flag,
//! which usage resolves at runtime) is dropped and counted, since winnow-args
//! resolves them at compile time.

use std::collections::HashSet;
use std::fs;

use crate::{Result, regex, root, rustfmt};

const SOURCE: &str = "benchmarks/shadows/mise/src/shadow.rs";
const TARGET: &str = "benchmarks/shadows/mise-wa/src/lib.rs";

/// Metadata winnow-args does not model; none of it changes how a line parses.
/// `value_optional` is what `default_missing` already says.
const DROP: &[&str] = &[
    "effect",
    "author",
    "bin",
    "mount",
    "value_enum",
    "var",
    "hide_default_value",
    "hide_env",
    "value_optional",
];
const KEEP: &[&str] = &[
    "long",
    "short",
    "alias",
    "alias_hidden",
    "value_name",
    "help",
    "long_help",
    "after_long_help",
    "help_heading",
    "hide",
    "global",
    "count",
    "subcommand",
    "default",
    "env",
    "delimiter",
    "choices",
    "double_dash",
    "required",
    "default_missing",
    "restart_token",
    "group",
    "disable_help_flag",
    "disable_version_flag",
    "default_subcommand",
    "about",
    "long_about",
];
const SELECTORS: &[&str] = &["conflicts", "overrides", "requires", "required_unless"];

/// The edits to the file around its attributes, each found exactly as written.
const REWRITES: &[(&str, &str)] = &[
    (
        "use usage_derive::{Args, Cli, Subcommands, ValueEnum};",
        "use winnow_args::{Args, Subcommand, ValueEnum};",
    ),
    (
        "#![allow(dead_code, unused_imports)]",
        "#![allow(dead_code, unused_imports)]\n\
         // mise's examples are indented like code blocks; they are not doctests.\n\
         #![cfg(not(doctest))]\n\
         #![allow(\n    rustdoc::broken_intra_doc_links,\n    rustdoc::bare_urls,\n    \
         rustdoc::invalid_html_tags,\n    rustdoc::invalid_rust_codeblocks\n)]",
    ),
    ("#[derive(Cli)]", "#[derive(Args)]"),
    ("#[derive(Subcommands)]", "#[derive(Subcommand)]"),
    (
        "#[derive(Args)]\n",
        "#[derive(Args)]\n#[arg(unknown_flags = \"value\")]\n",
    ),
    (
        "A shadow of `mise.usage.kdl` in usage's vocabulary, generated by\n\
         //! `cargo run -p xtask -- gen-shadow`.",
        "A shadow of `mise.usage.kdl` in winnow-args' vocabulary, translated from\n\
         //! usage's shadow by `cargo run -p xtask -- gen mise-shadow`.",
    ),
];

pub(crate) fn generate() -> Result<()> {
    let text = fs::read_to_string(root().join(SOURCE))?;
    let structs = owners(&text)?;
    let nothing = HashSet::new();
    let (mut out, mut last, mut dropped) = (String::new(), 0, 0);
    for (start, mut end, body) in attributes(&text)? {
        let local = structs
            .iter()
            .find(|s| s.start <= start && start < s.end)
            .map_or(&nothing, |s| &s.names);
        let items = split_top(body);
        let is_arg = items.iter().any(|item| item == "arg");
        let mut mapped = Vec::new();
        for item in &items {
            let key = key_of(item);
            if DROP.contains(&key) {
                continue;
            } else if key == "arg" {
                mapped.push("positional".to_owned());
            } else if key == "arg_required_else_help" {
                mapped.push(key.to_owned());
            } else if key == "name" && is_arg {
                mapped.push(item.replacen("name", "value_name", 1));
            } else if SELECTORS.contains(&key) {
                let named = strings_in(item);
                let kept: Vec<String> = named
                    .iter()
                    .filter(|s| local.contains(**s))
                    .map(|s| format!("\"{s}\""))
                    .collect();
                dropped += named.len() - kept.len();
                if !kept.is_empty() {
                    mapped.push(format!("{key}({})", kept.join(", ")));
                }
            } else if key == "name" || KEEP.contains(&key) {
                mapped.push(item.clone());
            } else {
                return Err(format!("unknown usage attribute `{key}` in: {item}").into());
            }
        }
        out.push_str(&text[last..start]);
        if mapped.is_empty() {
            // Nothing left: drop the attribute, its indentation and its line end.
            if text[end..].starts_with('\n') {
                end += 1;
            }
            out.truncate(out.trim_end_matches(' ').len());
        } else {
            out.push_str(&format!("#[arg({})]", mapped.join(", ")));
        }
        last = end;
    }
    out.push_str(&text[last..]);
    for (from, to) in REWRITES {
        out = out.replace(from, to);
    }
    let target = root().join(TARGET);
    fs::write(&target, out)?;
    rustfmt(&[&target])?;
    println!("wrote {TARGET}; dropped {dropped} selector(s) naming another struct's flag");
    Ok(())
}

/// A struct's span in the file, and the selectors its fields answer to.
struct Owner {
    start: usize,
    end: usize,
    names: HashSet<String>,
}

fn owners(text: &str) -> Result<Vec<Owner>> {
    let letter = regex("'(.)'");
    let mut owners = Vec::new();
    for found in regex(r"(?s)pub struct \w+ \{(.*?)\n\}").captures_iter(text) {
        let (whole, fields) = (found.get(0).expect("the match"), &found[1]);
        let mut names = HashSet::new();
        for (_, _, body) in attributes(fields)? {
            let items = split_top(body);
            let name = items.iter().rfind(|item| key_of(item) == "name");
            if let (true, Some(name)) = (items.iter().any(|item| key_of(item) == "arg"), name) {
                names.extend(strings_in(name).into_iter().map(str::to_owned));
            }
            for item in &items {
                match key_of(item) {
                    "long" | "alias" => {
                        names.extend(strings_in(item).into_iter().map(|s| format!("--{s}")));
                    }
                    "short" => {
                        let short = letter
                            .captures(item)
                            .ok_or_else(|| format!("no letter in `{item}`"))?;
                        names.insert(format!("-{}", &short[1]));
                    }
                    _ => {}
                }
            }
        }
        owners.push(Owner {
            start: whole.start(),
            end: whole.end(),
            names,
        });
    }
    Ok(owners)
}

/// `(start, end, body)` of every `#[usage(...)]`.
fn attributes(text: &str) -> Result<Vec<(usize, usize, &str)>> {
    const OPEN: &str = "#[usage(";
    let bytes = text.as_bytes();
    let mut found = Vec::new();
    for (start, _) in text.match_indices(OPEN) {
        let (mut i, mut depth) = (start + OPEN.len(), 1);
        while depth > 0 {
            match bytes[i] {
                b'"' => i = string_end(bytes, i),
                b'(' => depth += 1,
                b')' => depth -= 1,
                _ => {}
            }
            i += 1;
        }
        if bytes[i] != b']' {
            return Err(format!("unclosed attribute: {}", &text[start..=i]).into());
        }
        found.push((start, i + 1, &text[start + OPEN.len()..i - 1]));
    }
    Ok(found)
}

/// The closing quote of the string literal opening at `open`.
fn string_end(bytes: &[u8], open: usize) -> usize {
    let mut i = open + 1;
    while bytes[i] != b'"' {
        i += if bytes[i] == b'\\' { 2 } else { 1 };
    }
    i
}

/// The closing quote of the `char` literal opening at `open`, if it is one.
fn char_end(text: &str, open: usize) -> Option<usize> {
    let mut chars = text[open + 1..].char_indices();
    let (_, first) = chars.next()?;
    let (at, second) = chars.next()?;
    let at = open + 1 + at;
    if first == '\\' {
        let after = at + second.len_utf8();
        Some(after + text[after..].find('\'')?)
    } else {
        (second == '\'').then_some(at)
    }
}

/// An attribute's items: split on the commas outside strings, chars and parentheses.
fn split_top(text: &str) -> Vec<String> {
    let (mut items, mut depth, mut item, mut i) = (Vec::new(), 0, String::new(), 0);
    while let Some(c) = text[i..].chars().next() {
        let literal = match c {
            '"' => Some(string_end(text.as_bytes(), i)),
            '\'' => char_end(text, i),
            _ => None,
        };
        if let Some(end) = literal {
            item.push_str(&text[i..=end]);
            i = end + 1;
            continue;
        }
        match c {
            '(' => depth += 1,
            ')' => depth -= 1,
            _ => {}
        }
        if c == ',' && depth == 0 {
            items.push(item.trim().to_owned());
            item.clear();
        } else {
            item.push(c);
        }
        i += c.len_utf8();
    }
    if !item.trim().is_empty() {
        items.push(item.trim().to_owned());
    }
    items
}

/// `long` in `long = "x"`, `conflicts` in `conflicts("--y")`.
fn key_of(item: &str) -> &str {
    let end = item.find(|c: char| c.is_whitespace() || c == '=' || c == '(');
    &item[..end.unwrap_or(item.len())]
}

/// The contents of the string literals in `item`.
fn strings_in(item: &str) -> Vec<&str> {
    regex(r#""((?:[^"\\]|\\.)*)""#)
        .captures_iter(item)
        .map(|found| found.get(1).expect("a group").as_str())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn items_split_outside_literals_and_parentheses() {
        let items =
            split_top(r#"long = "a,b", short = ',', conflicts("--x", "--y"), help = "\"),""#);
        assert_eq!(
            items,
            [
                r#"long = "a,b""#,
                "short = ','",
                r#"conflicts("--x", "--y")"#,
                r#"help = "\"),""#,
            ]
        );
        assert_eq!(
            split_top(r"short = '\'', count"),
            [r"short = '\''", "count"]
        );
    }

    #[test]
    fn attributes_end_at_their_own_parenthesis() {
        let text = r#"#[usage(long = "a)]", requires("--b"))] x: bool, #[usage(arg)]"#;
        let bodies: Vec<&str> = attributes(text).unwrap().into_iter().map(|a| a.2).collect();
        assert_eq!(bodies, [r#"long = "a)]", requires("--b")"#, "arg"]);
    }

    #[test]
    fn keys_and_strings() {
        assert_eq!(key_of(r#"long = "x""#), "long");
        assert_eq!(key_of(r#"conflicts("--y")"#), "conflicts");
        assert_eq!(key_of("count"), "count");
        assert_eq!(strings_in(r#"alias("a", "b\"c")"#), ["a", r#"b\"c"#]);
    }
}
