#!/usr/bin/env python3
"""Regenerate winnow-args/examples/{brush_builtins,ld}.rs.

usage: tools/examples.py BRUSH_DIR MOLD_DIR

BRUSH_DIR is brush's `winnow-port` checkout, MOLD_DIR mold's
`winnow-args-cmdline` one. Both examples only print what they parse.
"""
import re, sys, os

brush, mold = sys.argv[1], sys.argv[2]
here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, '..', 'winnow-args', 'examples')

# ---------------------------------------------------------------- brush
BUILTINS = ['alias', 'cd', 'declare', 'echo', 'getopts', 'hash', 'history', 'kill', 'printf',
            'pwd', 'read', 'set', 'shopt', 'test', 'type_', 'umask', 'unset']

def derive_items(src):
    """Structs deriving winnow_args::Args, with their docs and attributes."""
    items = []
    lines = src.split('\n')
    for i, l in enumerate(lines):
        if l.startswith('#[derive(') and 'winnow_args::Args' in l:
            a = i
            while a > 0 and lines[a - 1].startswith('///'):
                a -= 1
            b = i
            while lines[b] != '}' and not re.match(r'^(pub(\(crate\))? )?struct \w+ \{\}$', lines[b]):
                b += 1
            items.append('\n'.join(lines[a:b + 1]))
    return items

structs, variants = [], []
for name in BUILTINS:
    src = open(f'{brush}/brush-builtins/src/{name}.rs').read()
    for item in derive_items(src):
        item = item.replace('pub(crate) struct', 'struct')
        item = re.sub(r'#\[derive\((Default, )?winnow_args::Args\)\]', '#[derive(Debug, Args)]', item)
        # Operands brush fills in itself are plain words here.
        item = item.replace('    #[arg(skip)]\n    declarations: Vec<brush_core::CommandArg>,',
                            '    /// Names and assignments.\n    #[arg(positional, stop_flags)]\n    declarations: Vec<String>,')
        ty = re.search(r'struct (\w+)', item).group(1)
        if ty.endswith('Command'):
            about = next((l[4:] for l in item.split('\n') if l.startswith('/// ')), '')
            cmd = name.rstrip('_')
            doc = f'    /// {about}\n' if about else ''
            variants.append(f'{doc}    #[arg(name = "{cmd}")]\n    {ty[:-7]}({ty}),')
        structs.append(item)

BRUSH = '''//! brush's builtins, as its `winnow-port` branch declares them: each parses
//! its arguments and prints what it got. Generated by `tools/examples.py`.
//!
//! ```text
//! cargo run --example brush_builtins -- set -eu +x -o pipefail a b
//! cargo run --example brush_builtins -- declare -i +x n=1
//! cargo run --example brush_builtins -- read -rp 'name: ' -t 2.5 first last
//! cargo run --example brush_builtins -- echo -n --help
//! cargo run --example brush_builtins -- kill --help
//! ```
//!
//! With `PARSE_N=n` in the environment the line is parsed `n` times and
//! nothing is printed, to measure the parse alone.

use std::path::PathBuf;

use winnow_args::{Args, Subcommand};

/// Parse a brush builtin's arguments and print the result.
#[derive(Debug, Args)]
#[arg(
    name = "brush_builtins",
    after_help = "Each builtin has its own `--help` (not `echo` and `test`, which take every word). \\
                  `set` and `declare` take `+x` options; `declare` stops at its first operand."
)]
struct Cli {
    #[arg(subcommand)]
    builtin: Builtin,
}

#[derive(Debug, Subcommand)]
#[allow(dead_code, reason = "the values are only printed")]
enum Builtin {
@VARIANTS@
}

@STRUCTS@

fn main() {
    let args: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();
    if let Some(n) = std::env::var("PARSE_N").ok().and_then(|n| n.parse::<usize>().ok()) {
        let words = winnow_args::words(&args);
        for _ in 0..n {
            let _ = std::hint::black_box(Cli::parse_from(std::hint::black_box(&words)));
        }
        return;
    }
    match Cli::try_parse_from(&args) {
        Ok(cli) => println!("{:#?}", cli.builtin),
        Err(error) => std::process::exit(winnow_args::report(&error, "brush_builtins")),
    }
}
'''
open(f'{out}/brush_builtins.rs', 'w').write(
    BRUSH.replace('@VARIANTS@', '\n'.join(variants)).replace('@STRUCTS@', '\n\n'.join(structs)))

# ---------------------------------------------------------------- mold
src = open(f'{mold}/src/cmdline_winnow.rs').read()
a = src.index('#[derive(Occurrence)]')
b = src.index('/// The whole command line')
enum = src[a:b].rstrip() + '\n'
enum = re.sub(r'\n    /// `--help`\.\n    #\[arg\(long = "help"\)\]\n    Help,', '', enum)
enum = re.sub(r'\n    #\[expect\(dead_code, reason = "accepted and ignored"\)\]', '', enum)
enum = enum.replace('#[derive(Occurrence)]', '#[derive(Occurrence, Debug)]').replace('pub(crate) enum', 'enum')
a = src.index('/// The option a `-z` keyword stands for')
b = src.index("/// An option's value as UTF-8")
zopt = src[a:b].rstrip().replace('pub(crate) fn', 'fn') + '\n'

# mold's own help text, by option, where it has one.
helps = {}
text = open(f'{mold}/src/cmdline.rs').read()
text = text[text.index('const HELP: &str = "'):]
text = text[:text.index('";')]
lines = text.split('\n')
for i, line in enumerate(lines):
    m = re.match(r'^  (-\S.*?)(?:\s{2,}(\S.*))?$', line)
    if not m:
        continue
    desc = m.group(2)
    if desc is None and i + 1 < len(lines) and re.match(r'^ {10,}\S', lines[i + 1]):
        # The option was too long: its description is on the next line.
        desc = lines[i + 1].strip()
    if desc is None:
        continue
    for spelling in m.group(1).split(', '):
        helps[spelling.split(' ')[0].split('=')[0].split('[')[0].lstrip('-')] = desc

def describe(m):
    spellings, attr = m.group(1), m.group(2)
    key = re.search(r"(?:short = '(.)'|long = \"([^\"]+)\")", attr)
    name = key.group(1) or key.group(2)
    doc = helps.get(name)
    return f'    /// {doc}\n    #[arg({attr})]' if doc else f'    /// {spellings}\n    #[arg({attr})]'
enum = re.sub(r'    /// (`-[^\n]*`)\n    #\[arg\(([^\n]*)\)\]', describe, enum)

LD = '''//! mold's command line, as its `winnow-args-cmdline` branch parses GNU ld's
//! options: every option is one variant of [`Item`], kept in order, and this
//! prints them. Generated by `tools/examples.py` from mold's parser.
//!
//! ```text
//! cargo run --example ld -- -shared -o out.so --as-needed -lc a.o -z now -zrelro
//! cargo run --example ld -- -sS --build-id --build-id=sha1 -L=usr/lib --lto-O2
//! cargo run --example ld -- @link.rsp
//! cargo run --example ld -- --help
//! ```
//!
//! With `PARSE_N=n` in the environment the line is parsed `n` times and
//! nothing is printed, to measure the parse alone.

use std::ffi::{OsStr, OsString};

use winnow_args::response::{ResponseFiles, expand};
use winnow_args::value::Spanned;
use winnow_args::{Args, Occurrence};

/// Print a GNU ld command line as mold reads it.
#[derive(Debug, Args)]
#[arg(
    name = "ld",
    long_only,
    disable_help_short,
    after_help = "Long options take one dash or two (`-shared`), except those listed with two only \\
                  where one dash would read as a short option's value. `-z KEYWORD` is printed as \\
                  the option it stands for; `@FILE` is replaced by the words in the file. A word \\
                  that is no option is an input; an unknown option is kept as `Unknown`, and \\
                  several short options in one word (`-sS`) as `Grouped` before them."
)]
struct Cli {
    #[arg(sequence, unknown)]
    items: Vec<Item>,
}

#[allow(dead_code, reason = "the values are only printed")]
@ENUM@
@ZOPT@
fn main() {
    let args: Vec<OsString> = std::env::args_os().skip(1).collect();
    let mut files = ResponseFiles::default();
    let words = match expand(&args, &mut files) {
        Ok(words) => words,
        Err(error) => {
            eprintln!("error: {error}");
            std::process::exit(2);
        }
    };
    if let Some(n) = std::env::var("PARSE_N").ok().and_then(|n| n.parse::<usize>().ok()) {
        for _ in 0..n {
            let _ = std::hint::black_box(Cli::parse_from(std::hint::black_box(&words)));
        }
        return;
    }
    match Cli::parse_from(&words) {
        Ok(cli) => {
            for item in cli.items {
                let item = match item {
                    Item::Z(z) => z_opt(&z.value).unwrap_or(Item::Z(z)),
                    item => item,
                };
                println!("{item:?}");
            }
        }
        Err(error) => std::process::exit(winnow_args::report(&error, "ld")),
    }
}
'''
open(f'{out}/ld.rs', 'w').write(LD.replace('@ENUM@', enum).replace('@ZOPT@', zopt))
