//! brush's builtins, as its `winnow-port` branch declares them: each parses
//! its arguments and prints what it got. Generated by `just gen examples`.
//! Do not edit: regenerate with `just gen examples BRUSH_DIR MOLD_DIR`.
//!
//! ```text
//! cargo run --example brush_builtins -- set -eu +x -o pipefail a b
//! cargo run --example brush_builtins -- declare -i +x n=1
//! cargo run --example brush_builtins -- read -rp 'name: ' -t 2.5 first last
//! cargo run --example brush_builtins -- echo -n --help
//! cargo run --example brush_builtins -- kill --help
//! ```
//!
//! With `PARSE_N=n` in the environment the line is parsed `n` times and
//! nothing is printed, to measure the parse alone.

use std::path::PathBuf;

use winnow_args::{Args, Subcommand};

/// Parse a brush builtin's arguments and print the result.
#[derive(Debug, Args)]
#[arg(
    name = "brush_builtins",
    after_help = "Each builtin has its own `--help` (not `echo` and `test`, which take every word). \
                  `set` and `declare` take `+x` options; `declare` stops at its first operand."
)]
struct Cli {
    #[arg(subcommand)]
    builtin: Builtin,
}

#[derive(Debug, Subcommand)]
enum Builtin {
@VARIANTS@
}

@STRUCTS@

fn main() {
    let args: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();
    if let Some(n) = std::env::var("PARSE_N").ok().and_then(|n| n.parse::<usize>().ok()) {
        let words = winnow_args::words(&args);
        for _ in 0..n {
            let _ = std::hint::black_box(Cli::parse_words(std::hint::black_box(&words)));
        }
        return;
    }
    match Cli::parse_from(&args) {
        Ok(cli) => println!("{:#?}", cli.builtin),
        Err(error) => std::process::exit(winnow_args::report(&error, "brush_builtins")),
    }
}
