//! mold's command line, as its `winnow-args-cmdline` branch parses GNU ld's
//! options: every option is one variant of [`Item`], kept in order, and this
//! prints them. Generated by `cargo run -p xtask -- gen examples` from mold's parser.
//!
//! ```text
//! cargo run --example ld -- -shared -o out.so --as-needed -lc a.o -z now -zrelro
//! cargo run --example ld -- -sS --build-id --build-id=sha1 -L=usr/lib --lto-O2
//! cargo run --example ld -- @link.rsp
//! cargo run --example ld -- --help
//! ```
//!
//! With `PARSE_N=n` in the environment the line is parsed `n` times and
//! nothing is printed, to measure the parse alone.

use std::ffi::{OsStr, OsString};

use winnow_args::response::{ResponseFiles, expand};
use winnow_args::value::Spanned;
use winnow_args::{Args, Occurrence};

/// Print a GNU ld command line as mold reads it.
#[derive(Debug, Args)]
#[arg(
    name = "ld",
    long_only,
    disable_help_short,
    after_help = "Long options take one dash or two (`-shared`), except those listed with two only \
                  where one dash would read as a short option's value. `-z KEYWORD` is printed as \
                  the option it stands for; `@FILE` is replaced by the words in the file. A word \
                  that is no option is an input; an unknown option is kept as `Unknown`, and \
                  several short options in one word (`-sS`) as `Grouped` before them."
)]
struct Cli {
    #[arg(sequence, unknown)]
    items: Vec<Item>,
}

#[allow(dead_code, reason = "the `-z` variants' values are only printed")]
@ENUM@
@ZOPT@
fn main() {
    let args: Vec<OsString> = std::env::args_os().skip(1).collect();
    let mut files = ResponseFiles::default();
    let words = match expand(&args, &mut files) {
        Ok(words) => words,
        Err(error) => {
            eprintln!("error: {error}");
            std::process::exit(2);
        }
    };
    if let Some(n) = std::env::var("PARSE_N").ok().and_then(|n| n.parse::<usize>().ok()) {
        for _ in 0..n {
            let _ = std::hint::black_box(Cli::parse_words(std::hint::black_box(&words)));
        }
        return;
    }
    match Cli::parse_words(&words) {
        Ok(cli) => {
            for item in cli.items {
                let item = match item {
                    Item::Z(z) => z_opt(&z.value).unwrap_or(Item::Z(z)),
                    item => item,
                };
                println!("{item:?}");
            }
        }
        Err(error) => std::process::exit(winnow_args::report(&error, "ld")),
    }
}
